mkey/leaderboard_viewer/urls.py
from django.urls import path

from .views import IndexView

app_name = 'leaderboard_viewer'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

mkey/mkey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leaderboard_viewer.urls'))
]

mkey/leaderboard_viewer/models.py
from django.db import models

# Create your models here.

mkey/leaderboard_viewer/views.py
# Create your views here.
import json
import re

import asyncio
from functools import partial

import requests
from django.shortcuts import render
from django.views import generic
from multiprocessing.pool import Pool

ACCESS_TOKEN_STRING = "&access_token=gebaggfxv5f9r2bjyzma3p2u"
GET_REALM_INFO_URL = "https://eu.api.battle.net/data/wow/realm/{0}?namespace=dynamic-eu&locale=en_GB"+ACCESS_TOKEN_STRING
GET_MYTHIC_LEADERBOARD_URL = "https://eu.api.battle.net/data/wow/connected-realm/{0}/mythic-leaderboard/?namespace=dynamic-eu&locale=en_GB"+ACCESS_TOKEN_STRING


class IndexView(generic.View):
    def get(self, request):
        return render(request, template_name='leaderboard_viewer/index.html')

    def post(self, request):
        try:
            realm_lowest_keys = get_realm_lowest_keys(request.POST["dungeon"], request.POST["wow_input"])
            error_message = ""
        except ValueError as error:
            realm_lowest_keys = None
            error_message = str(error)
        except:
            realm_lowest_keys = None
            error_message = "Something unexpected went terribly wrong. Yikes!"

        return render(request, 'leaderboard_viewer/index.html',
                      {"previous_player_input": request.POST["wow_input"], "realm_lowest_keys": realm_lowest_keys,
                       "dungeon_name": request.POST["dungeon"], "error_message": error_message})


class PlayerData:
    realm = ""
    name = ""

    def __init__(self, name, realm):
        self.name = name
        self.realm_regexp = re.compile('[A-Za-z][^A-Z]*')
        self.realm = self.git_real_realm_name(realm)

    def __str__(self):
        return "{0}-{1}".format(self.name, self.realm.capitalize())

    def git_real_realm_name(self, realm):
        # handle realms like Quel'Thalas, Anub'arak
        if "'" in realm:
            return realm.replace("'", "").lower()

        # handle realms like TarrenMill, GrimBatol
        return "-".join(self.realm_regexp.findall(realm)).lower()


DUNGEONS = {
    "Atal'dazar": 244,
    'Freehold': 245,
    'Tol Dagor': 246,
    'The MOTHERLODE!!': 247,
    'Waycrest Manor': 248,
    "Kings' Rest": 249,
    'Temple of Sethraliss': 250,
    'The Underrot': 251,
    'Shrine of the Storm': 252,
    'Siege of Boralus': 353
}


def get_realm_lowest_keys(dungeon, player_wow_input):
    dungeon_id = DUNGEONS[dungeon]
    player_wow_input = player_wow_input.strip()
    if not isinstance(player_wow_input, list):
        player_wow_input = player_wow_input.split("\n")
    players = []
    for player_input in player_wow_input:
        if "] " in player_input:
            # handles input copied from the game, this will be in the format of
            # [time] <Name>-<Realm>, and splits the input into [name, realm] for each player
            player_and_realm = player_input.split("] ")[1].strip().split("-")
        elif "-" in player_input:
            # handles when just the <Name>-<Realm> is provided
            player_and_realm = player_input.split("-")
        else:
            # handles when only the realm is specified
            player_and_realm = ["Vowyrin", player_input]

        # unpacks the list of 2 things -> [name, realm]
        player_data = PlayerData(*player_and_realm)
        players.append(player_data)

    p = Pool(min(5, len(player_wow_input)))

    # Create a queue that we will use to store our "workload".
    realm_data_requests = partial(retrieve_realm_data, dungeon_id)

    result = p.imap(realm_data_requests, players)

    p.close()
    p.join()

    realms_lowest_keys = []
    for r in result:
        realms_lowest_keys.append(r)

    # sort by key level
    return sorted(realms_lowest_keys, key=lambda x: x[1])


def retrieve_realm_data(dungeon_id, player):
    response = requests.get(GET_REALM_INFO_URL.format(player.realm))

    if response.status_code != 200:
        raise ValueError("Request to Blizzard did not succeed.")
    print(response.text)
    realm_info_json = json.loads(response.text)
    # +1 moves the index in front of the slash
    connected_id_start = realm_info_json["connected_realm"]["href"].rfind(
        "/") + 1
    connected_id_end = realm_info_json["connected_realm"]["href"].rfind("?")
    connected_id = realm_info_json["connected_realm"]["href"][
                   connected_id_start:connected_id_end]
    print("Connected realm id", connected_id)

    mythic_leaderboard_response = requests.get(
        GET_MYTHIC_LEADERBOARD_URL.format(connected_id))
    mythic_leaderboard_json = json.loads(mythic_leaderboard_response.text)

    for leaderboard in mythic_leaderboard_json["current_leaderboards"]:
        if leaderboard["id"] == dungeon_id:
            leaderboard_response = requests.get(leaderboard["key"]["href"] +
                                                "&" + ACCESS_TOKEN_STRING)
            leaderboard_json = json.loads(leaderboard_response.text)
            last_group = leaderboard_json["leading_groups"][-1]
            seconds = (last_group["duration"] / 1000) % 60
            minutes = (last_group["duration"] / (1000 * 60)) % 60
            print("Last group level", last_group["keystone_level"], "Duration",
                  "{0}m {1}s".format(minutes, seconds))
            return [str(player), last_group["keystone_level"], "{0}m {1}s".format(int(minutes), int(seconds))]

mkey/leaderboard_viewer/templates/leaderboard_viewer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>M+ Lowest Key Level Checker</title>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <style>
    .padding-bottom {
      padding-bottom: 5px;
    }

    .margin-y {
      margin-bottom: 3rem;
      margin-top: 3rem;
    }

    .full-width {
      width: 100%;
    }

    .common-body {
      border-color: #5b5b5b;
      color: #e1ded5;
      background-color: #202128;
    }

    .code {
      border-radius: 5px;
      border: 1px solid #5b5b5b;
      overflow-x: scroll;
    }
  </style>
  <script>
    function copyMacroToClipboard(button) {
      let e = document.getElementById('macro-code');
      const el = document.createElement('textarea');
      el.value = e.textContent;
      el.setAttribute('readonly', '');
      el.style.position = 'absolute';
      el.style.left = '-9999px';
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
      let message = document.createElement("p");
      message.classList.add("full-width");
      message.style.textAlign = "center";
      message.textContent = "Successful!";
      button.parentElement.appendChild(message);
      setTimeout(() => {
        button.parentElement.removeChild(message);
      }, 2000);
    }
    function selectDungeon(dungeonName){
        const select = document.getElementById("dungeon-selection");
        for(let child of select.children){
            if(child.textContent===dungeonName){
                child.selected=true;
                break;
            }
        }
    }
  </script>
</head>
<body class="common-body">
<div class="w3-col l4">&nbsp;</div>
<div class="w3-col s12 m12 l4">
  Put this in a macro - it will give you a list of all party members' names and realms that you have to copy paste
  below.
  <div class="code">
    <code>
      <pre id="macro-code">/run print(format("%s-%s", UnitFullName("player")))
/run for i=1,GetNumGroupMembers()-1 do local u="party"..i print(format("%s-%s",UnitFullName(u))) end
</pre>
    </code>
    <button type="button" class="w3-button w3-border full-width"
            onclick="copyMacroToClipboard(this)">Copy to Clipboard
    </button>
  </div>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
  {% if realm_lowest_keys %}
    <div class="margin-y w3-border">
    <p style="text-align:center">Showing the lowest key on each realm for: {{ dungeon_name }}</p>
      <table class="w3-table">
        <thead>
        <th>Player</th>
        <th>Lowest Key</th>
        <th>Time</th>
        </thead>
        <tbody>
        {% for l in realm_lowest_keys %}
          <tr>
            <td>{{ l.0 }}</td>
            <td>{{ l.1 }}</td>
            <td>{{ l.2 }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
  <form method="post" action="{% url 'leaderboard_viewer:index' %}">
    {% csrf_token %}
    <div class="padding-bottom">
      <label>Dungeon<br>
          <select id="dungeon-selection" class="w3-select w3-border common-body full-width" name="dungeon">
          <option>Atal'dazar</option>
          <option>Freehold</option>
          <option>Tol Dagor</option>
          <option>The MOTHERLODE!!</option>
          <option>Waycrest Manor</option>
          <option>Kings' Rest</option>
          <option>Temple of Sethraliss</option>
          <option>The Underrot</option>
          <option>Shrine of the Storm</option>
          <option>Siege of Boralus</option>
        </select>
        <script>
            selectDungeon("{{ dungeon_name }}");
        </script>
      </label>
    </div>
    <div>
      <label>Player Names:<br>
        <textarea class="w3-input w3-border common-body full-width" style="margin-right:15px" rows="15"
                  name="wow_input">{{ previous_player_input }}</textarea>
      </label>
    </div>
    <br>
    <button class="w3-button w3-border full-width">Find lowest key</button>
  </form>
</div>
<div class="w3-col l4">&nbsp;</div>
</body>
</html>